### ISSUE TITLE
Update to CPLEX 12.10

### ISSUE THREAD

**Issue by beyeler** [marketdesignresearch/mechlib#19]
CPLEX 12.10 arrived and it has some major improvements (e.g faster QP solver). Therfore I suggest to update mechlib and all related projects to CPLEX 12.10.

**Comment by islerfab** [comment]
Since this JAR is provided by the user, all we need to do in our projects (e.g., mechlib), is to change the `12.9` to `12.10` in our `pom.xml`, and make sure we have CPLEX 12.10 installed locally, with the CLASSPATH updated (the way we did it for 12.9). I saw that you've done but reverted this in the MLCA branch, was that not working as I'm expecting it?
In any case, I should release a new version of JOpt with this updated dependency, such that there are no potential conflicts.

**Comment by beyeler** [comment]
I have it up and running with CPLEX 12.10. And I agree, it is more a JOpt issue, so I might should have raised it there. Adapting mechlib and sats is straight forward as you suggested. But in my point of view we should change the JOpt version at the same time.

**Comment by islerfab** [comment]
I had to re-instantiate the publishing pipeline, especially because my GPG keys were expired. I changed JOpt, though: https://github.com/blubin/JOpt/pull/19
It takes a while for the new key to be available in the keyservers, and then I will push the button to release it on Maven Central, and then it takes another few hours to be indexed there.
I will notice you when that's done, and then you can include JOpt 1.3.5 in the MLCA branch, such that we don't need a PR for this small change. Ok?

**Comment by islerfab** [comment]
Update: The keyserver has refreshed, so the JOpt 1.3.5 is released - it will be indexed and thus available as a dependency in a few hours.

**Comment by beyeler** [comment]
Thx works perfect. Closing this issue.
